require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MadlogicOne' do
  use_frameworks!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'MadlogicOneTests' do
    inherit! :complete
    # Pods for testing
  end

  # Without flipper
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      #    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
      #    end

      target.build_configurations.each do |config|
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
      end
    end
  end
end

target 'MadlogicOne-tvOS' do
  # Pods for MadlogicOne-tvOS

  target 'MadlogicOne-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end