require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MadlogicOne' do
  use_frameworks!

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  target 'MadlogicOneTests' do
    inherit! :complete
    # Pods for testing
  end

  # Without flipper
  pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
    # Convert all permission pods into static libraries
    installer.pod_targets.each do |pod|
      if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
        def pod.build_type;
          # Uncomment one line depending on your CocoaPods version
          Pod::BuildType.static_library # >= 1.9
          # Pod::Target::BuildType.static_library # < 1.9
        end
      end
    end
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      #    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
      #    end

      target.build_configurations.each do |config|
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
      end
    end
  end
end

target 'MadlogicOne-tvOS' do
  # Pods for MadlogicOne-tvOS

  target 'MadlogicOne-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end